"make distclean" failed because an output file from one test was not removed
"
ERROR: files left in build directory after distclean:
./test/output.h5m
"


git-svn-id: https://svn.mcs.anl.gov/repos/ITAPS/MOAB/trunk@4752 6162379e-bd28-0410-9a7d-b7f4dcfcad3c